name: light_updater
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  http: ^0.13.5
  path_provider: ^2.0.14
  window_manager: ^0.3.1
  crypto: ^3.0.2
  quiver: ^3.2.1
  archive: ^3.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - "assets/images/app_icon.ico"

  fonts:
  - family: VarelaRound
    fonts:
      - asset: assets/fonts/VarelaRound.ttf
